# Generated by Django 2.1.2 on 2018-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catssports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
