# Generated by Django 2.1.2 on 2018-11-24 22:55

from django.db import migrations
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = '123'
    superuser.email = '123@admin.net'
    superuser.set_password('catssportsshamelesslyexposedinrepopassword')
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catssports', '0003_video_people'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
