# Generated by Django 2.1.2 on 2018-11-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catssports', '0006_video_errored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('wrong_hand_angle', 'wrong_hand_angle'), ('wrong_spine_angle', 'wrong_spine_angle')], default='wrong_hand_angle', max_length=100)),
            ],
        ),
    ]
