# Generated by Django 2.1.2 on 2018-11-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catssports', '0007_mistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistake',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='catssports.Video'),
        ),
    ]
