# Generated by Django 2.1.2 on 2018-11-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catssports', '0008_mistake_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mistake',
            old_name='group',
            new_name='video',
        ),
    ]
